### ISSUE TITLE
Unhandled exception when test fails

### ISSUE THREAD

**Issue by ninjatronic** [lazd/gulp-karma#23]
When I have a test that fails I get the following exception:

```
/Users/pete/work/projects/console/node_modules/gulp-karma/index.js:56
        stream.emit('error', new gutil.PluginError('gulp-karma', 'karma exited
                             ^
TypeError: undefined is not a function
  at done (/Users/pete/work/projects/console/node_modules/gulp-karma/index.js:56:30)
  at ChildProcess.<anonymous> (/Users/pete/kinvey/projects/console/node_modules/gulp-karma/index.js:82:7)
  at ChildProcess.EventEmitter.emit (events.js:98:17)
  at Process.ChildProcess._handle.onexit (child_process.js:797:12)
```

Which breaks the pipe.

**Comment by lazd** [comment]
`gulp-karma` is deprecated (#43). Please use Karma directly: https://github.com/karma-runner/gulp-karma
