### ISSUE TITLE
Error: No provider for "framework:jasmine"

### ISSUE THREAD

**Issue by hhelwich** [lazd/gulp-karma#4]
i get the following error:

```
./node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)
    at error (./node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (./node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (./node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at ./node_modules/gulp-karma/node_modules/karma/lib/server.js:29:14
    at Array.forEach (native)
    at start (./node_modules/gulp-karma/node_modules/karma/lib/server.js:28:21)
    at invoke (./node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (./node_modules/gulp-karma/node_modules/karma/lib/server.js:272:12)
    at Object.<anonymous> (./node_modules/gulp-karma/lib/background.js:3:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

If i start karma from console it works as expected (`./node_modules/.bin/karma run`).

**Comment by DominicTobias** [comment]
Sadly this did not fix anything, my devDependencies looks like:

```"jasmine-core": "^2.2.0",
"karma": "^0.12.31",
"karma-chrome-launcher": "^0.1.7",
"karma-htmlfile-reporter": "^0.1.2",
"karma-jasmine": "^0.3.5",
"karma-jasmine-jquery": "^0.1.1",
"karma-phantomjs-launcher": "^0.1.4",
"karma-requirejs": "^0.2.2",```

config:

```frameworks: ['jasmine-jquery', 'requirejs', 'jasmine'],```

but then as soon as I add ```plugins: []``` even with nothing inside, it fails on whatever the first item is in that list:

```Error: No provider for "framework:jasmine-jquery"! (Resolving: framework:jasmine-jquery)```

Any ideas?

**Comment by mmahalwy** [comment]
hmm having this problem now :(

**Comment by quantuminformation** [comment]
I'm having this issue, I'm only wanting to run mocha.

`Error: No provider for "framework:mocha"! (Resolving: framework:mocha)`

my conf:

``` js
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['mocha'],
    files: [
      'src/**/*.js', 'src/**/__spec__/*.js'
    ],
    exclude: [],
    preprocessors: {},
    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome', 'IE', 'PhantomJS', 'Safari', 'Firefox'],
    singleRun: false,
    concurrency: Infinity
  })
}
```

related package:

``` js
    "gulp-watch": "^1.1.0",
    "jasmine": "^2.3.1",
    "jasmine-core": "^2.4.1",
    "jscs": "^1.7.3",
    "jshint": "^2.5.6",
    "karma-jasmine": "^0.3.6",
    "minimist": "^1.1.0",
    "mocha": "^2.3.4",
```

I'm running Karma through webstorm.

**Comment by gesilar** [comment]
i had the issue before,and i solved this problem by install karma concerned modules to global env.it`s a directly way  to run your test modules but not the best way to solve the problem.

**Comment by reddynr** [comment]
I am getting error below error while running karma test. anybody have work around. much appreciated. Thanks

Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)

**Comment by reddynr** [comment]
here is my karma.config file. any help much appreciated. Thanks

// Karma configuration
// Generated on Thu Oct 13 2016 12:05:23 GMT-0400 (Eastern Daylight Time)

module.exports = function(config) {
  config.set({

```
// base path that will be used to resolve all patterns (eg. files, exclude)
basePath: '',


// frameworks to use
// available frameworks: https://npmjs.org/browse/keyword/karma-adapter
frameworks: ['jasmine'],


// list of files / patterns to load in the browser
```

   // list of files / patterns to load in the browser
files: [
  'lib/angular.min.js',
  'lib/angular-mocks.js',
  'app/_.js',
  'tests/_.js'
],

```
// list of files to exclude
exclude: [
],


// preprocess matching files before serving them to the browser
// available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
preprocessors: {
},


// test results reporter to use
// possible values: 'dots', 'progress'
// available reporters: https://npmjs.org/browse/keyword/karma-reporter
reporters: ['progress'],


// web server port
port: 9876,


// enable / disable colors in the output (reporters and logs)
colors: true,


// level of logging
// possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
logLevel: config.LOG_INFO,


// enable / disable watching file and executing tests whenever any file changes
autoWatch: true,


// start these browsers
// available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
browsers: ['Chrome'],


// Continuous Integration mode
// if true, Karma captures browsers, runs the tests and exits
singleRun: false,

// Concurrency level
// how many browser should be started simultaneous
concurrency: Infinity
```

  })
}

**Comment by segevsh** [comment]
I struggled with the exact same problem. After investigating I realized that karma was running globally using '/usr/' directory as the base folder.

A solution that worked for me was to replace karma with karma-cli:

```
    npm remove -g karma
    npm install -g karma-cli
```
